#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.0 (December 31, 2017)
# creation date: Wed Feb 12 02:17:03 2020

# ---------------------- set process variables ----------------------

set dirA = /Volumes/reynalab/Lab/HotCold/Databases/HC_1stHalfFunctional/Output/fmriprep

# specify and possibly create results directory
set results_dir = test.results
if ( ! -d $results_dir ) mkdir $results_dir

# ------------------------- process the data -------------------------

3dttest++ -prefix $results_dir/NHAdu-NHAdo_NoCov_F-NF -AminusB   \
          -setA NonHungryAdults                                   \
            028 "$dirA/sub-028/func/statsStart.028+tlrc[25]" \
            038 "$dirA/sub-038/func/statsStart.038+tlrc[25]" \
            047 "$dirA/sub-047/func/statsStart.047+tlrc[25]" \
            048 "$dirA/sub-048/func/statsStart.048+tlrc[25]" \
            049 "$dirA/sub-049/func/statsStart.049+tlrc[25]" \
            050 "$dirA/sub-050/func/statsStart.050+tlrc[25]" \
            051 "$dirA/sub-051/func/statsStart.051+tlrc[25]" \
            058 "$dirA/sub-058/func/statsStart.058+tlrc[25]" \
            059 "$dirA/sub-059/func/statsStart.059+tlrc[25]" \
            061 "$dirA/sub-061/func/statsStart.061+tlrc[25]" \
            062 "$dirA/sub-062/func/statsStart.062+tlrc[25]" \
            065 "$dirA/sub-065/func/statsStart.065+tlrc[25]" \
            066 "$dirA/sub-066/func/statsStart.066+tlrc[25]" \
            067 "$dirA/sub-067/func/statsStart.067+tlrc[25]" \
            068 "$dirA/sub-068/func/statsStart.068+tlrc[25]" \
            070 "$dirA/sub-070/func/statsStart.070+tlrc[25]" \
            073 "$dirA/sub-073/func/statsStart.073+tlrc[25]" \
            074 "$dirA/sub-074/func/statsStart.074+tlrc[25]" \
            075 "$dirA/sub-075/func/statsStart.075+tlrc[25]" \
            076 "$dirA/sub-076/func/statsStart.076+tlrc[25]" \
            086 "$dirA/sub-086/func/statsStart.086+tlrc[25]" \
            088 "$dirA/sub-088/func/statsStart.088+tlrc[25]" \
            089 "$dirA/sub-089/func/statsStart.089+tlrc[25]" \
            101 "$dirA/sub-101/func/statsStart.101+tlrc[25]" \
            119 "$dirA/sub-119/func/statsStart.119+tlrc[25]" \
            123 "$dirA/sub-123/func/statsStart.123+tlrc[25]" \
          -setB NonHungryAdolescents                                   \
            001 "$dirA/sub-001/func/statsStart.001+tlrc[25]" \
            002 "$dirA/sub-002/func/statsStart.002+tlrc[25]" \
            003 "$dirA/sub-003/func/statsStart.003+tlrc[25]" \
            005 "$dirA/sub-005/func/statsStart.005+tlrc[25]" \
            006 "$dirA/sub-006/func/statsStart.006+tlrc[25]" \
            007 "$dirA/sub-007/func/statsStart.007+tlrc[25]" \
            013 "$dirA/sub-013/func/statsStart.013+tlrc[25]" \
            022 "$dirA/sub-022/func/statsStart.022+tlrc[25]" \
            025 "$dirA/sub-025/func/statsStart.025+tlrc[25]" \
            036 "$dirA/sub-036/func/statsStart.036+tlrc[25]" \
            037 "$dirA/sub-037/func/statsStart.037+tlrc[25]" \
            052 "$dirA/sub-052/func/statsStart.052+tlrc[25]" \
            053 "$dirA/sub-053/func/statsStart.053+tlrc[25]" \
            055 "$dirA/sub-055/func/statsStart.055+tlrc[25]" \
            056 "$dirA/sub-056/func/statsStart.056+tlrc[25]" \
            060 "$dirA/sub-060/func/statsStart.060+tlrc[25]" \
            072 "$dirA/sub-072/func/statsStart.072+tlrc[25]" \
            078 "$dirA/sub-078/func/statsStart.078+tlrc[25]" \
            079 "$dirA/sub-079/func/statsStart.079+tlrc[25]" \
            080 "$dirA/sub-080/func/statsStart.080+tlrc[25]" \
            081 "$dirA/sub-081/func/statsStart.081+tlrc[25]" \
            082 "$dirA/sub-082/func/statsStart.082+tlrc[25]" \
            090 "$dirA/sub-090/func/statsStart.090+tlrc[25]" \
            102 "$dirA/sub-102/func/statsStart.102+tlrc[25]" \
            114 "$dirA/sub-114/func/statsStart.114+tlrc[25]" \
            116 "$dirA/sub-116/func/statsStart.116+tlrc[25]" \
            117 "$dirA/sub-117/func/statsStart.117+tlrc[25]" \
            118 "$dirA/sub-118/func/statsStart.118+tlrc[25]" \
            122 "$dirA/sub-122/func/statsStart.122+tlrc[25]" \
            124 "$dirA/sub-124/func/statsStart.124+tlrc[25]" \
            129 "$dirA/sub-129/func/statsStart.129+tlrc[25]" \
            130 "$dirA/sub-130/func/statsStart.130+tlrc[25]" \
            131 "$dirA/sub-131/func/statsStart.131+tlrc[25]" \
            132 "$dirA/sub-132/func/statsStart.132+tlrc[25]"
