#!/bin/tcsh -xef

# created by uber_ttest.py: version 2.0 (December 37, 2017)
# creation date: Wed Feb 12 02:17:03 2020

# ---------------------- set process variables ----------------------

set dirA = /Volumes/Reyna-Lab/Lab/HotCold/Databases/HC_1stHalfFunctional/Output/fmriprep

# specify and possibly create results directory
set results_dir = test.results
if ( ! -d $results_dir ) mkdir $results_dir

# ------------------------- process the data -------------------------

3dttest++ -Clustsim -prefix $results_dir/ISDNNHAdo_NoCov_LG-SG  \
          -mask $dirA/fullHC_mask+tlrc \
          -AminusB   \
          -setA NonHungryAdolescents \
             001 "$dirA/sub-001/func/stats.ISDN001+tlrc[49]" \
             002 "$dirA/sub-002/func/stats.ISDN002+tlrc[49]" \
             003 "$dirA/sub-003/func/stats.ISDN003+tlrc[49]" \
             005 "$dirA/sub-005/func/stats.ISDN005+tlrc[49]" \
             006 "$dirA/sub-006/func/stats.ISDN006+tlrc[49]" \
             007 "$dirA/sub-007/func/stats.ISDN007+tlrc[49]" \
             013 "$dirA/sub-013/func/stats.ISDN013+tlrc[49]" \
             022 "$dirA/sub-022/func/stats.ISDN022+tlrc[49]" \
             025 "$dirA/sub-025/func/stats.ISDN025+tlrc[49]" \
             027 "$dirA/sub-027/func/stats.ISDN027+tlrc[49]" \
             029 "$dirA/sub-029/func/stats.ISDN029+tlrc[49]" \
             030 "$dirA/sub-030/func/stats.ISDN030+tlrc[49]" \
             032 "$dirA/sub-032/func/stats.ISDN032+tlrc[49]" \
             033 "$dirA/sub-033/func/stats.ISDN033+tlrc[49]" \
             034 "$dirA/sub-034/func/stats.ISDN034+tlrc[49]" \
             035 "$dirA/sub-035/func/stats.ISDN035+tlrc[49]" \
             036 "$dirA/sub-036/func/stats.ISDN036+tlrc[49]" \
             037 "$dirA/sub-037/func/stats.ISDN037+tlrc[49]" \
             052 "$dirA/sub-052/func/stats.ISDN052+tlrc[49]" \
             053 "$dirA/sub-053/func/stats.ISDN053+tlrc[49]" \
             055 "$dirA/sub-055/func/stats.ISDN055+tlrc[49]" \
             056 "$dirA/sub-056/func/stats.ISDN056+tlrc[49]" \
             060 "$dirA/sub-060/func/stats.ISDN060+tlrc[49]" \
             069 "$dirA/sub-069/func/stats.ISDN069+tlrc[49]" \
             072 "$dirA/sub-072/func/stats.ISDN072+tlrc[49]" \
             078 "$dirA/sub-078/func/stats.ISDN078+tlrc[49]" \
             079 "$dirA/sub-079/func/stats.ISDN079+tlrc[49]" \
             080 "$dirA/sub-080/func/stats.ISDN080+tlrc[49]" \
             081 "$dirA/sub-081/func/stats.ISDN081+tlrc[49]" \
             082 "$dirA/sub-082/func/stats.ISDN082+tlrc[49]" \
             085 "$dirA/sub-085/func/stats.ISDN085+tlrc[49]" \
             087 "$dirA/sub-087/func/stats.ISDN087+tlrc[49]" \
             090 "$dirA/sub-090/func/stats.ISDN090+tlrc[49]" \
             091 "$dirA/sub-091/func/stats.ISDN091+tlrc[49]" \
             092 "$dirA/sub-092/func/stats.ISDN092+tlrc[49]" \
             093 "$dirA/sub-093/func/stats.ISDN093+tlrc[49]" \
             094 "$dirA/sub-094/func/stats.ISDN094+tlrc[49]" \
             095 "$dirA/sub-095/func/stats.ISDN095+tlrc[49]" \
             096 "$dirA/sub-096/func/stats.ISDN096+tlrc[49]" \
             097 "$dirA/sub-097/func/stats.ISDN097+tlrc[49]" \
             099 "$dirA/sub-099/func/stats.ISDN099+tlrc[49]" \
             100 "$dirA/sub-100/func/stats.ISDN100+tlrc[49]" \
             102 "$dirA/sub-102/func/stats.ISDN102+tlrc[49]" \
             103 "$dirA/sub-103/func/stats.ISDN103+tlrc[49]" \
             104 "$dirA/sub-104/func/stats.ISDN104+tlrc[49]" \
             105 "$dirA/sub-105/func/stats.ISDN105+tlrc[49]" \
             106 "$dirA/sub-106/func/stats.ISDN106+tlrc[49]" \
             107 "$dirA/sub-107/func/stats.ISDN107+tlrc[49]" \
             108 "$dirA/sub-108/func/stats.ISDN108+tlrc[49]" \
             109 "$dirA/sub-109/func/stats.ISDN109+tlrc[49]" \
             110 "$dirA/sub-110/func/stats.ISDN110+tlrc[49]" \
             111 "$dirA/sub-111/func/stats.ISDN111+tlrc[49]" \
             113 "$dirA/sub-113/func/stats.ISDN113+tlrc[49]" \
             114 "$dirA/sub-114/func/stats.ISDN114+tlrc[49]" \
             116 "$dirA/sub-116/func/stats.ISDN116+tlrc[49]" \
             117 "$dirA/sub-117/func/stats.ISDN117+tlrc[49]" \
             118 "$dirA/sub-118/func/stats.ISDN118+tlrc[49]" \
             121 "$dirA/sub-121/func/stats.ISDN121+tlrc[49]" \
             122 "$dirA/sub-122/func/stats.ISDN122+tlrc[49]" \
             124 "$dirA/sub-124/func/stats.ISDN124+tlrc[49]" \
             129 "$dirA/sub-129/func/stats.ISDN129+tlrc[49]" \
             130 "$dirA/sub-130/func/stats.ISDN130+tlrc[49]" \
             131 "$dirA/sub-131/func/stats.ISDN131+tlrc[49]" \
             132 "$dirA/sub-132/func/stats.ISDN132+tlrc[49]"
